development:
  session_key: eldorado_development
  session_secret: ESl6X3oKM1i1RRrD2QLwUUzz9jr1zxNO
  domain: http://example.com

test:
  session_key: eldorado_test
  session_secret: vrwPpJTvwnMVLP1wTSgqigSl7PMI7QcE
  domain: http://example.com

production:
  # SESSION SETTINGS (required)
  # More info: http://guides.rubyonrails.org/security.html#session-storage
  session_key: <%= ENV['BUSHIDO_DOMAIN'] %> # a unique string that identifies your app
  session_secret: asdfjaskdlfajefji4fjio4nf3oi4fn34ufn3ui4f2n3fun23dnn # a random string, at least 32 characters long, that should be unique to your installation and kept secret

  # APPLICATION SETTINGS (required)
  domain: <%= ENV['PUBLIC_URL'] %> # http://example.com # the url for your application
  mailer: noreply@<%= ENV['BUSHIDO_DOMAIN'] %> # noreply@example.com # the from address for subscription emails (users can subscribe to forum threads)

  # AMAZON S3 (optional, required for Heroku)
  # More info from Heroku: http://docs.heroku.com/constraints#read-only-filesystem
  # Visit the Amazon S3 site to sign up for an access_id and secret_key: https://s3.amazonaws.com/
  # The bucket name can be any unique string, and once set here it can be created by running "rake s3:create"
  s3_access_id:
  s3_secret_key:
  s3_bucket_name:

  # AMAZON CLOUDFRONT (optional)
  # You can sign up for CloudFront (http://aws.amazon.com/cloudfront) and provide the CNAME here
  s3_host_alias: # assets.example.com

  # EMAIL SETTINGS (optional, required for Heroku)
  # More info from Heroku: http://support.heroku.com/forums/43117/entries/32352
  # These example settings would use a normal Gmail account, but other options are available...
  smtp_address: <%= ENV['SMTP_SERVER'] %> # smtp.gmail.com
  smtp_port: <%= ENV['SMTP_PORT'] %> # 587
  smtp_user_name: <%= ENV['SMTP_USER'] %> # example@gmail.com
  smtp_password: <%= ENV['SMTP_PASSWORD'] %> # password
  smtp_authentication: <%= ENV['SMTP_AUTHENTICATION'] %> # plain
  smtp_enable_starttls_auto: <%= ENV['SMTP_TLS'] %> # true
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %> # example.com # omit if using a normal Gmail account

  # HOPTOAD (optional)
  hoptoad_key: # Sign up at http://hoptoadapp.com and provide your API key to recieve exception notification emails

  # LOCALE (optional)
  locale: # Choose a locale from config/locales, en is the default

  # DISABLE TABS (optional)
  disabled_tabs: # list tabs that want to hide from users (e.g. "blog events headers")
